#数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            stat-view-servlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                loginUsername: admin
                loginPassword: 12358
        dynamic:
            druid: 
                # 初始连接数
                initial-size: 5
                # 最大连接池数量
                max-active: 20
                # 最小连接池数量
                min-idle: 10
                # 配置获取连接等待超时的时间
                max-wait: 60000
                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
                time-between-eviction-runs-millis: 60000
                # 配置一个连接在池中最小生存的时间，单位是毫秒
                min-evictable-idle-time-millis: 300000
                # 配置一个连接在池中最大生存的时间，单位是毫秒
                max-evictable-idle-time-millis: 900000
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                validation-query: SELECT 1
                filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
                wall:
                    multiStatementAllow: true
                stat:
                    merge-sql: true
                    log-slow-sql: true
                    slow-sql-millis: 1000
            datasource:
                master:
                    username: root
                    password: 123581321
                    #driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/pbc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    druid: # 以下参数针对每个库可以重新设置druid参数
                        validation-query: select 1
                slave1:
                    username: sa
                    password: ""
                    driver-class-name: org.h2.Driver
                    url: jdbc:h2:mem:test
                    schema: classpath:db/schema-demo.sql
                    data: classpath:db/data-demo.sql
                    druid: # 以下参数针对每个库可以重新设置druid参数
                        validation-query: select 1
                slave2:
                    username: sa
                    password: ""
                    driver-class-name: org.h2.Driver
                    url: jdbc:h2:mem:test
                    schema: classpath:db/schema-demo.sql
                    data: classpath:db/data-demo.sql
                    druid: # 以下参数针对每个库可以重新设置druid参数
                        validation-query: select 1
                        
    # redis 配置
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 密码
        password: 123456
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                  
                    
                    
                    
                    
